// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDmCiHsgtup7O-ny81aNS8z9AziNO-kecs',
    appId: '1:178669994094:web:a76771b1eb6226065c667f',
    messagingSenderId: '178669994094',
    projectId: 'chat-app-f1e2e',
    authDomain: 'chat-app-f1e2e.firebaseapp.com',
    storageBucket: 'chat-app-f1e2e.firebasestorage.app',
    measurementId: 'G-JFKJFDRD3J',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBsHnkXq7HLbJn9N3hT2GScb4yM_Q7umWc',
    appId: '1:178669994094:android:9e2a5a5fd432d1055c667f',
    messagingSenderId: '178669994094',
    projectId: 'chat-app-f1e2e',
    storageBucket: 'chat-app-f1e2e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA0SyLlXvVjH8bZsQuV-TvZSLTVPstSUTw',
    appId: '1:178669994094:ios:ac5697b47bea7f215c667f',
    messagingSenderId: '178669994094',
    projectId: 'chat-app-f1e2e',
    storageBucket: 'chat-app-f1e2e.firebasestorage.app',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA0SyLlXvVjH8bZsQuV-TvZSLTVPstSUTw',
    appId: '1:178669994094:ios:ac5697b47bea7f215c667f',
    messagingSenderId: '178669994094',
    projectId: 'chat-app-f1e2e',
    storageBucket: 'chat-app-f1e2e.firebasestorage.app',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDmCiHsgtup7O-ny81aNS8z9AziNO-kecs',
    appId: '1:178669994094:web:73def0a348a7935a5c667f',
    messagingSenderId: '178669994094',
    projectId: 'chat-app-f1e2e',
    authDomain: 'chat-app-f1e2e.firebaseapp.com',
    storageBucket: 'chat-app-f1e2e.firebasestorage.app',
    measurementId: 'G-PRZXG30YLY',
  );
}
